version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto17
      # AWS托管的构建容器
  build:
    commands:
      - echo "Building Lambda with Maven..."
      - mvn clean package -DskipTests #skip test
      - mkdir -p output
      - cp target/java-lambda-demo-1.0-SNAPSHOT.jar output/lambda.jar #copy the JAR file to output/
  post_build:
    commands:
      - echo "Uploading to S3..."
      - aws s3 cp output/lambda.jar s3://lambdahelloworldbucket1/lambda-output/lambda.jar
      # 复制jar到output目录

artifacts:
  base-directory: output
  files:
    - lambda.jar
